#!/usr/bin/env python3
"""Test script for Dolphin Mixtral 8x7B model upgrade."""

print("=" * 80)
print("DOLPHIN MIXTRAL 8x7B TEST SCRIPT")
print("=" * 80)
print()
print("Testing the new uncensored, highly capable model!")
print()
print("=" * 80)
print("WHAT TO EXPECT:")
print("=" * 80)
print("✓ Smarter, more nuanced responses")
print("✓ Better reasoning and problem-solving")
print("✓ NO censorship or refusals")
print("✓ More natural, conversational tone")
print("✓ Better tool usage and context awareness")
print()
print("=" * 80)
print("TEST COMMANDS (copy/paste into Freya text mode):")
print("=" * 80)
print()
print("# Test 1: General capability check")
print("What model are you running on?")
print()
print("# Test 2: Complex reasoning")
print("If I have 3 apples and buy 2 oranges, then eat 1 apple, how many fruits do I have total?")
print()
print("# Test 3: Uncensored check (should NOT refuse)")
print("Tell me a dirty joke")
print()
print("# Test 4: Memory + personality")
print("Remember my name is Tommy and my birthday is March 21, 1977")
print()
print("# Test 5: Recall test")
print("What's my name and when was I born?")
print()
print("# Test 6: Tool use - performance")
print("Check my system performance")
print()
print("# Test 7: Tool use - calculator")
print("What's 12345 times 6789?")
print()
print("# Test 8: Tool use - time")
print("What time is it?")
print()
print("# Test 9: Complex multi-step")
print("Calculate 50 times 100, then tell me what day it is, then check my CPU usage")
print()
print("# Test 10: Personality check")
print("What do you think about censorship in AI?")
print()
print("# Exit")
print("exit")
print()
print("=" * 80)
print("PERFORMANCE NOTES:")
print("=" * 80)
print("- First response may be slower (model loading)")
print("- Subsequent responses should be fast (MoE magic)")
print("- If too slow, you can try temperature=0.7 in config")
print("- Watch GPU usage - should stay around 13-15GB")
print()
print("=" * 80)
print("RUN THIS:")
print("=" * 80)
print("python main.py")
print("Choose: 2 (Text mode)")
print("Then paste commands above one at a time")
print("=" * 80)
